exports.constants = {
  //apiUrl
  apiUrl : 'http://localhost:3000/api',
  //action type
<<<<<<< Updated upstream
  LOGIN_SUCCESS : 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  POPUP_LOGIN: 'POPUP_LOGIN',
  HIDE_POPUP: 'HIDE_POPUP'
}
=======
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  POPUP_LOGIN: "POPUP_LOGIN",
  HIDE_POPUP: "HIDE_POPUP",
  
  GET_TEST_SUCCESS: "GET_TEST_SUCCESS",
  GET_TEST_FAILURE: "GET_TEST_FAILURE",
  GET_TESTS_SUCCESS: "GET_TESTS_SUCCESS",
  GET_TESTS_FAILURE: "GET_TESTS_FAILURE",
  GET_HOME_SUCCESS: "GET_HOME_SUCCESS",
  GET_HOME_FAILURE: "GET_HOME_FAILURE",
  GET_QUESTIONS_FAILURE : "GET_QUESTIONS_FAILURE",
  GET_QUESTIONS_SUCCESS : "GET_QUESTIONS_SUCCESS",

  DASHBOARD_TEST: "DASHBOARD_TEST",
  DASHBOARD_QUESTION: "DASHBOARD_QUESTION",

  LOADING: "LOADING",
  FAILURE: "FAILURE",
  SUCCESS: "SUCCESS",
  //mode
  DO_TEST_MODE: "DO_TEST_MODE",
  SUBMITED_MODE: "SUBMITED_MODE",
  SHOW_EXPLANATION_MODE: "SHOW_EXPLANATION_MODE",
};
>>>>>>> Stashed changes
