exports.constants = {
  //apiUrl
  apiUrl: "https://fathomless-castle-76283.herokuapp.com/api",
  //action type
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  POPUP_LOGIN: "POPUP_LOGIN",
  HIDE_POPUP: "HIDE_POPUP",
  GET_TEST_SUCCESS: "GET_TEST_SUCCESS",
  GET_TEST_FAILURE: "GET_TEST_FAILURE",
  LOADING: "LOADING",
  FAILURE: "FAILURE",
  SUCCESS: "SUCCESS",
  //mode
  DO_TEST_MODE: "DO_TEST_MODE",
  SUBMITED_MODE: "SUBMITED_MODE",
  SHOW_EXPLANATION_MODE: "SHOW_EXPLANATION_MODE",
};
